export const Images = [
  {
    id: "1",
    url: "/donuts1.png",
    name: "Glaze",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "2",
    url: "/cookie_monster.png",
    name: "Chocolate Ring",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "3",
    url: "/unicorn.png",
    name: "Chocolate Sprinkle",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "4",
    url: "/reeses.png",
    name: "Maple Ring",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "5",
    url: "/donuts1.png",
    name: "Maple Sprinkle",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "6",
    url: "/cookie_monster.png",
    name: "Vanilla Sprinkle",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "7",
    url: "/unicorn.png",
    name: "Pink Sprinkle",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "8",
    url: "/reeses.png",
    name: "Blueberry Cake",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "9",
    url: "/donuts1.png",
    name: "Vanilla Cake",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "10",
    url: "/cookie_monster.png",
    name: "Zebra Bar",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "11",
    url: "/unicorn.png",
    name: "Maple Bar",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "12",
    url: "/reeses.png",
    name: "Chocolate Bar",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "13",
    url: "/reeses.png",
    name: "Old Fashion",
    type: "classic",
    price: "1.59",
    description: "",
  },
  {
    id: "14",
    url: "/reeses.png",
    name: "Cow",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "15",
    url: "/unicorn.png",
    name: "Circus Animal",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "16",
    url: "/cookie_monster.png",
    name: "Unicorn",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "17",
    url: "/reeses.png",
    name: "Cookie Monster",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "18",
    url: "/unicorn.png",
    name: "Mermaid",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "19",
    url: "/cookie_monster.png",
    name: "Shark",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "20",
    url: "/reeses.png",
    name: "Cinnamon Toast",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "21",
    url: "/unicorn.png",
    name: "M&M",
    type: "deluxe",
    price: "1.99",
    description: "",
  },
  {
    id: "22",
    url: "/reeses.png",
    name: "Oreo",
    type: "deluxe",
    price: "1.99",
    description: "",
  },
  {
    id: "23",
    url: "/unicorn.png",
    name: "Samoa",
    type: "deluxe",
    price: "1.99",
    description: "",
  },
  {
    id: "24",
    url: "/cookie_monster.png",
    name: "Espresso",
    type: "deluxe",
    price: "1.99",
    description: "",
  },
  {
    id: "25",
    url: "/reeses.png",
    name: "Cookie Butter",
    type: "deluxe",
    price: "1.99",
    description: "",
  },
  {
    id: "26",
    url: "/unicorn.png",
    name: "Whipped Cream",
    type: "deluxe",
    price: "1.99",
    description: "",
  },
  {
    id: "27",
    url: "/cookie_monster.png",
    name: "Reeses Whip",
    type: "deluxe",
    price: "1.99",
    description: "",
  },
  {
    id: "28",
    url: "/cookie_monster.png",
    name: "Cinnamon Roll",
    type: "deluxe",
    price: "1.99",
    description: "",
  },
  {
    id: "29",
    url: "/reeses.png",
    name: "Raspberry, Lemon and Strawberry Filled",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "30",
    url: "/unicorn.png",
    name: "Custard",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "31",
    url: "/cookie_monster.png",
    name: "Maple Bacon",
    type: "deluxe",
    price: "2.49",
    description: "",
  },
  {
    id: "32",
    url: "/reeses.png",
    name: "Apple Fritter",
    type: "deluxe",
    price: "1.89",
    description: "",
  },
  {
    id: "33",
    url: "/unicorn.png",
    name: "Peach Fritter",
    type: "deluxe",
    price: "1.89",
    description: "Sat-Sun Only",
  },
];

export default Images;
