import Carouselv2 from "@/components/Carouselv2";
import Navbarz from "@/components/Navbar";
import RightMenu from "@/components/RightMenu";
import React from "react";
import images from "../../data";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Hello Donuts | Donuts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>
        <div className="flex flex-col h-screen">
          <Navbar />
          {/* Content Area */}
          <div className="flex-grow overflow-hidden">{children}</div>
          {/* Carousel at the Bottom */}
          <div className="carousel-container">
            <Carouselv2 images={images} />
          </div>
        </div>
      </body>
    </html>
  );
}
