import Carouselv2 from "@/components/Carouselv2";
import Navbarz from "@/components/Navbar";
import RightMenu from "@/components/RightMenu";
import React from "react";
import images from "../../data";

export const metadata = {
  title: "Hello Donuts | Donuts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="coffee">
      <body>
        <Navbarz />
        {children}
        {/* <div className="grid max-w-6xl grid-cols-6 mx-auto">
          <div className="col-span-4">{children}</div>
          <div className="col-span-2">
            <RightMenu />
          </div>
        </div> */}

        <div className="relative max-w-6xl min-h-screen mx-auto">
          <div className="absolute max-w-6xl mx-auto bottom-32">
            <Carouselv2 images={images} />
          </div>
        </div>
      </body>
    </html>
  );
}
